# Generated by Django 4.2.23 on 2025-06-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TOPS', 'Top'), ('BOTTOMS', 'Bottom'), ('OUTER', 'Outer'), ('ONEPIECE', 'One-piece'), ('ETC', 'Etc')], max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
