// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLs3GZCemF-KYuvXXU_rcN94Zhpo_tCas',
    appId: '1:619861201734:web:80f45ef46f4e3f30ffcb47',
    messagingSenderId: '619861201734',
    projectId: 'outfitterai-4cc7e',
    authDomain: 'outfitterai-4cc7e.firebaseapp.com',
    storageBucket: 'outfitterai-4cc7e.firebasestorage.app',
    measurementId: 'G-W3WDF6FRCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkFTFuD9oVxu0Z7CxO-CedRnhPOgSJLaQ',
    appId: '1:619861201734:android:f2a5b04cbe7afa0fffcb47',
    messagingSenderId: '619861201734',
    projectId: 'outfitterai-4cc7e',
    storageBucket: 'outfitterai-4cc7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfmfxxYYd-FkSusmLJTaXwRwc-eXBsPmg',
    appId: '1:619861201734:ios:19c989ae8bb24465ffcb47',
    messagingSenderId: '619861201734',
    projectId: 'outfitterai-4cc7e',
    storageBucket: 'outfitterai-4cc7e.firebasestorage.app',
    iosBundleId: 'com.honoka.fashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfmfxxYYd-FkSusmLJTaXwRwc-eXBsPmg',
    appId: '1:619861201734:ios:96693d639f31014effcb47',
    messagingSenderId: '619861201734',
    projectId: 'outfitterai-4cc7e',
    storageBucket: 'outfitterai-4cc7e.firebasestorage.app',
    iosBundleId: 'com.example.fashionFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLs3GZCemF-KYuvXXU_rcN94Zhpo_tCas',
    appId: '1:619861201734:web:59aa13bb7bbe505affcb47',
    messagingSenderId: '619861201734',
    projectId: 'outfitterai-4cc7e',
    authDomain: 'outfitterai-4cc7e.firebaseapp.com',
    storageBucket: 'outfitterai-4cc7e.firebasestorage.app',
    measurementId: 'G-JYX36EBLV0',
  );
}
